[configuration]
workers = "10"

[BasicPing]
use = "check_ping.Ping"
warn_RTT = "10"
crit_RTT = "20"
warn_loss = "20"
crit_loss = "40"

[CheckCert]
use = "check_nagios.Nagios"
command = "/usr/lib/monitoring-plugins/check_http"
cmdopts = "-C!30,15"
interval = "86400, 86400, 86400, 600"
changecount = "1"

[NagiosPing]
use = "check_nagios.Nagios"
command = "/usr/lib/monitoring-plugins/check_ping"
cmdopts = "-w!10,20%!-c!20,40%"

[CheckHttps]
use = "check_nagios.Nagios"
command = "/usr/lib/monitoring-plugins/check_http"
cmdopts = "--ssl"
interval = "600, 600, 600, 30"
changecount = "2"

[CheckSSH]
use = "check_nagios.Nagios"
command = "/usr/lib/monitoring-plugins/check_ssh"
interval = "600, 600, 600, 30"
changecount = "3"

[CheckDisk]
use = "check_nagios.Nagios"
command = "/usr/lib/monitoring-plugins/check_disk "
cmdopts = "-w!10%!-c!5%"
interval = "3600,1800,600,30"
changecount = "1"
host = "none"

[Router]
host = "172.17.2.254"
group = "internal"
enabled = "true"
CheckCert = "none"
CheckHttps = "none"
basicping = "none"

[Belle]
host = "172.17.2.35"
group = "internal"
enabled = "true"
CheckSSH = ""
basicping = ""

[Storm]
host = "172.17.4.53"
group = "media"
enabled = "true"
CheckSSH = ""
basicping = ""

[Sighrun]
host = "sighrun.orthoefer.org"
group = "internal"
enabled = "true"
basicping = ""
CheckCert = ""
CheckHttps = " cmdopts=--ssl!-u!https://sighrun.orthoefer.org/index.php?title=Main_Page"
CheckSSH = ""
CheckDisk = ""

[Ariel]
host = "172.17.2.36"
group = "internal"
enabled = "true"
CheckSSH = ""
basicping = ""

[sw-office]
hostname = "sw-office.orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.18"
basicping = ""

[cam3]
hostname = "cam3.orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.25"
basicping = ""

[nvr]
hostname = "nvr.orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.32"
basicping = ""


[sw-LivingRm]
hostname = "sw-LivingRm.Orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.37"
basicping = ""

[sw-kitchen]
hostname = "sw-kitchen.orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.41"
basicping = ""

[Giselle]
hostname = "Giselle.orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.42"
basicping = ""

[vpn]
hostname = "vpn.orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.64"
basicping = ""

[kara]
hostname = "kara"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.114"
basicping = ""

[HP8A32AE]
hostname = "HP8A32AE.Orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.146"
basicping = ""

[AirCam]
hostname = "AirCam.Orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.182"
basicping = ""

[animalkingdom]
hostname = "animalkingdom.Orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.185"
basicping = ""

[SallyCarrera]
hostname = "SallyCarrera.Orthoefer.org"
group = "internal"
enabled = "false"
ipv4 = "172.17.2.208"
basicping = ""

[Amanda]
hostname = "Amanda.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.10"
basicping = ""

[HDHR-13112D36]
hostname = "HDHR-13112D36.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.107"
basicping = ""

[amazon-d303b2051]
hostname = "amazon-d303b2051.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.108"
basicping = ""

[LivingRAppleTV2]
hostname = "LivingRAppleTV2.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.112"
basicping = ""

[Google-Home-Mini]
hostname = "Google-Home-Mini.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.120"
basicping = ""

[FamilyRAppleTV9]
hostname = "FamilyRAppleTV9.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.126"
basicping = ""

[amazon-6ba89fea2]
hostname = "amazon-6ba89fea2.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.140"
basicping = ""

[amazon-71f9b2050]
hostname = "amazon-71f9b2050.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.160"
basicping = ""

[KitchenAppleTV]
hostname = "KitchenAppleTV.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.198"
basicping = ""

[amazon-5bd0ce6c0]
hostname = "amazon-5bd0ce6c0.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.227"
basicping = ""

[amazon-047047b68]
hostname = "amazon-047047b68.Orthoefer.org"
group = "media"
enabled = "false"
ipv4 = "172.17.4.238"
basicping = ""

[Jasmine]
hostname = "Jasmine.orthoefer.org"
group = "security"
enabled = "false"
ipv4 = "172.31.31.31"
basicping = ""

[router]
hostname = "router.verizon.net"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.1"
basicping = ""

[Rapunzel]
hostname = "Rapunzel.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.12"
basicping = ""

[TIVO-746000190A9D4CC]
hostname = "TIVO-746000190A9D4CC.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.121"
basicping = ""

[RIPE-Atlas-Probe-4549]
hostname = "RIPE-Atlas-Probe-4549.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.129"
basicping = ""

[BedroomAppleTV]
hostname = "BedroomAppleTV.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.134"
basicping = ""

[Wireless_Broadband_Router]
hostname = "Wireless_Broadband_Router.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.143"
basicping = ""

[cs_0024b10000023ee9]
hostname = "cs_0024b10000023ee9.Orthoefer.org"
group = "vzn"
enabled = "false"
ipv4 = "192.168.0.223"
basicping = ""

